// Keywords for SEO
export const keywords = [
  "XyPriss",
  "Node.js Framework",
  "Rust Web Framework", // Still relevant for legacy/search, but README says Native/Go now
  "Hybrid Framework",
  "High Performance",
  "Enterprise Web Apps",
  "TypeScript",
  "Go Engine",
  "XHSC",
  "XFPM",
  "XEMS",
  "Zero-Trust Security",
  "Encrypted Sessions",
  "Radix Routing",
  "Environment Security Shield",
  "XStatic Engine",
  "Binary Streaming",
  "Backend Fortress",
  "Nehonix",
  "Developer Velocity",
  "Secure by Default",
  "AES-256-GCM",
  "Zero-Copy IPC",
  "XStatic Engine",
  "XEMS Technical Suite",
  "Native URI Normalization",
  "Anti-ReDoS Engine",
  "Honeypot Tarpit",
  "Multi-Server Isolation",
  "Hybrid Go TypeScript",
];